import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5 import uic, QtCore, QtGui, QtWidgets
import threading


#UI class
class initialUi(object):
    def setupUi(self, initial):
        initial.setObjectName("initial")
        initial.resize(500, 900)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        initial.setPalette(palette)
        initial.setStyleSheet("backgournd: rgb(255, 255, 255)")
        self.gridLayoutWidget = QtWidgets.QWidget(initial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 504, 901))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 700, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.orderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.orderBtn.setFont(font)
        self.orderBtn.setAutoFillBackground(False)
        self.orderBtn.setStyleSheet("background: rgb(184, 61, 0)")
        self.orderBtn.setCheckable(True)
        self.orderBtn.setObjectName("orderBtn")
        self.gridLayout.addWidget(self.orderBtn, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.managerBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.managerBtn.setStyleSheet("background:rgba(255, 255, 255, 0)")
        self.managerBtn.setText("")
        self.managerBtn.setObjectName("managerBtn")
        self.gridLayout.addWidget(self.managerBtn, 0, 0, 1, 1)

        self.retranslateUi(initial)
        QtCore.QMetaObject.connectSlotsByName(initial)

    def retranslateUi(self, initial):
        _translate = QtCore.QCoreApplication.translate
        initial.setWindowTitle(_translate("initial", "Dialog"))
        self.orderBtn.setText(_translate("initial", "o r d e r"))

class mainUi(object): #메인화면 UI
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(500, 900)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        main.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        main.setFont(font)
        main.setStyleSheet("background: rgb(255, 255, 255)")
        self.verticalLayoutWidget = QtWidgets.QWidget(main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 901))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.egg_image = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.egg_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.egg_image.sizePolicy().hasHeightForWidth())
        self.egg_image.setSizePolicy(sizePolicy)
        self.egg_image.setMinimumSize(QtCore.QSize(0, 0))
        self.egg_image.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("아리따-부리_TTF_SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.egg_image.setFont(font)
        self.egg_image.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.egg_image.setIndent(0)
        self.egg_image.setObjectName("egg_image")
        self.verticalLayout.addWidget(self.egg_image)
        self.menuGrid = QtWidgets.QGridLayout()
        self.menuGrid.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.menuGrid.setContentsMargins(-1, -1, -1, 0)
        self.menuGrid.setSpacing(0)
        self.menuGrid.setObjectName("menuGrid")
        self.misterEggBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.misterEggBtn.sizePolicy().hasHeightForWidth())
        self.misterEggBtn.setSizePolicy(sizePolicy)
        self.misterEggBtn.setMinimumSize(QtCore.QSize(100, 100))
        self.misterEggBtn.setMaximumSize(QtCore.QSize(200, 100))
        self.misterEggBtn.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.misterEggBtn.setFont(font)
        self.misterEggBtn.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.misterEggBtn.setObjectName("misterEggBtn")
        self.menuGrid.addWidget(self.misterEggBtn, 0, 0, 1, 1)
        self.americanHamBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.americanHamBtn.setMinimumSize(QtCore.QSize(100, 100))
        self.americanHamBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.americanHamBtn.setFont(font)
        self.americanHamBtn.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.americanHamBtn.setObjectName("americanHamBtn")
        self.menuGrid.addWidget(self.americanHamBtn, 0, 1, 1, 1)
        self.baconDoubleBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.baconDoubleBtn.setMinimumSize(QtCore.QSize(100, 100))
        self.baconDoubleBtn.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.baconDoubleBtn.setFont(font)
        self.baconDoubleBtn.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.baconDoubleBtn.setObjectName("baconDoubleBtn")
        self.menuGrid.addWidget(self.baconDoubleBtn, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.menuGrid)
        self.menulistLayout = QtWidgets.QVBoxLayout()
        self.menulistLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.menulistLayout.setObjectName("menulistLayout")
        self.verticalLayout.addLayout(self.menulistLayout)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Dialog"))
        self.egg_image.setText(_translate("main", "EGG DROP"))
        self.misterEggBtn.setText(_translate("main", "미스터 에그\n"
                                                         "3,400원"))
        self.americanHamBtn.setText(_translate("main", "아메리칸햄치즈\n"
                                                           "3,900원"))
        self.baconDoubleBtn.setText(_translate("main", "베이컨 더블치즈\n"
                                                           "4,200원"))

class menuUi(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(500, 900)
        menu.setMaximumSize(QtCore.QSize(500, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        menu.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        menu.setFont(font)
        menu.setStyleSheet("background: rgb(255, 255, 255)")
        self.verticalLayoutWidget = QtWidgets.QWidget(menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 901))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_2.addWidget(self.nameLabel)
        self.detailLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        self.detailLabel.setFont(font)
        self.detailLabel.setIndent(-1)
        self.detailLabel.setObjectName("detailLabel")
        self.verticalLayout_2.addWidget(self.detailLabel)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bunBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bunBtn.sizePolicy().hasHeightForWidth())
        self.bunBtn.setSizePolicy(sizePolicy)
        self.bunBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Thin")
        font.setPointSize(12)
        self.bunBtn.setFont(font)
        self.bunBtn.setIconSize(QtCore.QSize(19, 19))
        self.bunBtn.setTristate(False)
        self.bunBtn.setObjectName("bunBtn")
        self.horizontalLayout.addWidget(self.bunBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.eggBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.eggBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Thin")
        font.setPointSize(12)
        self.eggBtn.setFont(font)
        self.eggBtn.setObjectName("eggBtn")
        self.horizontalLayout_2.addWidget(self.eggBtn)
        self.pollackBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pollackBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Thin")
        font.setPointSize(12)
        self.pollackBtn.setFont(font)
        self.pollackBtn.setObjectName("pollackBtn")
        self.horizontalLayout_2.addWidget(self.pollackBtn)
        self.avocadoBtn = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.avocadoBtn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Thin")
        font.setPointSize(12)
        self.avocadoBtn.setFont(font)
        self.avocadoBtn.setObjectName("avocadoBtn")
        self.horizontalLayout_2.addWidget(self.avocadoBtn)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_3.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.returnBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.returnBtn.setFont(font)
        self.returnBtn.setToolTip("")
        self.returnBtn.setStyleSheet("background: rgb(184, 62, 14)")
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout_4.addWidget(self.returnBtn)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.okBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        self.okBtn.setFont(font)
        self.okBtn.setStyleSheet("background: rgb(184, 62, 14)")
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_4.addWidget(self.okBtn)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Dialog"))
        self.nameLabel.setText(_translate("menu", "베이컨 더블치즈"))
        self.detailLabel.setText(
            _translate("menu", "<html><head/><body><p>베이컨이</p><p>더블치즈와</p><p>만났 다!</p></body></html>"))
        self.label.setText(_translate("menu", "빵 변경"))
        self.bunBtn.setText(_translate("menu", "번\n"
                                                  "+0원"))
        self.label_2.setText(_translate("menu", "추가 토핑"))
        self.eggBtn.setText(_translate("menu", "계란\n"
                                                  "+200원"))
        self.pollackBtn.setText(_translate("menu", "명란\n"
                                                      "+500원"))
        self.avocadoBtn.setText(_translate("menu", "아보카도\n"
                                                      "+700원"))
        self.returnBtn.setText(_translate("menu", "이전단계"))
        self.okBtn.setText(_translate("menu", "선택 완료"))

class takeoutUi(object):
    def setupUi(self, takeout):
        takeout.setObjectName("takeout")
        takeout.resize(500, 784)
        takeout.setMaximumSize(QtCore.QSize(500, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        takeout.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        takeout.setFont(font)
        takeout.setStyleSheet("background: rgb(255, 255, 255)")
        self.verticalLayoutWidget = QtWidgets.QWidget(takeout)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 901))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.inBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.inBtn.setMinimumSize(QtCore.QSize(0, 100))
        self.inBtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        self.inBtn.setFont(font)
        self.inBtn.setStyleSheet("background: rgb(225, 225, 225)")
        self.inBtn.setObjectName("inBtn")
        self.horizontalLayout_3.addWidget(self.inBtn)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.outBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.outBtn.setMinimumSize(QtCore.QSize(0, 100))
        self.outBtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        self.outBtn.setFont(font)
        self.outBtn.setStyleSheet("background: rgb(225, 225, 225)")
        self.outBtn.setObjectName("outBtn")
        self.horizontalLayout_3.addWidget(self.outBtn)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 600))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.returnBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.returnBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.returnBtn.setFont(font)
        self.returnBtn.setToolTip("")
        self.returnBtn.setStyleSheet("background: rgb(184, 62, 14)")
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout_4.addWidget(self.returnBtn)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(takeout)
        QtCore.QMetaObject.connectSlotsByName(takeout)

    def retranslateUi(self, takeout):
        _translate = QtCore.QCoreApplication.translate
        takeout.setWindowTitle(_translate("takeout", "Dialog"))
        self.name_label.setText(_translate("takeout", "takeout"))
        self.label_3.setText(_translate("takeout", "포장 여부를 선택해 주세요"))
        self.inBtn.setText(_translate("takeout", "매장에서"))
        self.outBtn.setText(_translate("takeout", "포장"))
        self.returnBtn.setText(_translate("takeout", "이전단계"))

class paymentUi(object):
    def setupUi(self, payment):
        payment.setObjectName("payment")
        payment.resize(500, 900)
        payment.setMaximumSize(QtCore.QSize(500, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        payment.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        payment.setFont(font)
        payment.setStyleSheet("background: rgb(255, 255, 255)")
        self.verticalLayoutWidget = QtWidgets.QWidget(payment)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 502, 935))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name_label.setMinimumSize(QtCore.QSize(0, 100))
        self.name_label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Thin")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 300))
        self.label_4.setMaximumSize(QtCore.QSize(100, 300))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.moenyInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.moenyInput.setObjectName("moenyInput")
        self.horizontalLayout_2.addWidget(self.moenyInput)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(35, 50))
        self.label_2.setMaximumSize(QtCore.QSize(35, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 300))
        self.label_5.setMaximumSize(QtCore.QSize(100, 300))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 100))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 200))
        self.label_8.setMaximumSize(QtCore.QSize(50, 200))
        font = QtGui.QFont()
        font.setFamily("-윤고딕310")
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.returnBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.returnBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.returnBtn.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.returnBtn.setFont(font)
        self.returnBtn.setToolTip("")
        self.returnBtn.setStyleSheet("background: rgb(184, 62, 14)")
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout_4.addWidget(self.returnBtn)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 200))
        self.label_9.setMaximumSize(QtCore.QSize(100, 200))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(payment)
        QtCore.QMetaObject.connectSlotsByName(payment)

    def retranslateUi(self, payment):
        _translate = QtCore.QCoreApplication.translate
        payment.setWindowTitle(_translate("payment", "Dialog"))
        self.label_3.setText(_translate("payment", "| 결제 화면 |"))
        self.label.setText(_translate("payment", "입력란에 투입할 금액을 입력해 주세요"))
        self.label_2.setText(_translate("payment", "원"))
        self.returnBtn.setText(_translate("payment", "← 이전화면으로 돌아가기"))

class managementUi(object):
    def setupUi(self, management):
        management.setObjectName("management")
        management.resize(500, 833)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        management.setPalette(palette)
        management.setStyleSheet("backgournd: rgb(255, 255, 255)")
        self.managerTab = QtWidgets.QTabWidget(management)
        self.managerTab.setGeometry(QtCore.QRect(0, 40, 501, 861))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Bold")
        font.setPointSize(16)
        self.managerTab.setFont(font)
        self.managerTab.setObjectName("managerTab")
        self.menu_tab = QtWidgets.QWidget()
        self.menu_tab.setObjectName("menu_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menu_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 471, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 50))
        self.label_2.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 50))
        self.label_3.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.plus_btn = QtWidgets.QPushButton(self.menu_tab)
        self.plus_btn.setGeometry(QtCore.QRect(350, 740, 131, 61))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        self.plus_btn.setFont(font)
        self.plus_btn.setObjectName("plus_btn")
        self.managerTab.addTab(self.menu_tab, "")
        self.stock_tab = QtWidgets.QWidget()
        self.stock_tab.setObjectName("stock_tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.stock_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 471, 791))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yearBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.yearBtn.setFont(font)
        self.yearBtn.setObjectName("yearBtn")
        self.horizontalLayout_3.addWidget(self.yearBtn)
        self.monthBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.monthBtn.setFont(font)
        self.monthBtn.setObjectName("monthBtn")
        self.horizontalLayout_3.addWidget(self.monthBtn)
        self.dayBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(14)
        self.dayBtn.setFont(font)
        self.dayBtn.setObjectName("dayBtn")
        self.horizontalLayout_3.addWidget(self.dayBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.today_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.today_label.setText("")
        self.today_label.setObjectName("today_label")
        self.horizontalLayout_4.addWidget(self.today_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(50, 30))
        self.label_7.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(290, 30))
        self.label_8.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Medium")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.order_list = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.order_list.setMinimumSize(QtCore.QSize(50, 0))
        self.order_list.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Light")
        font.setPointSize(12)
        self.order_list.setFont(font)
        self.order_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.order_list.setObjectName("order_list")
        self.horizontalLayout_8.addWidget(self.order_list)
        self.menu_list = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.menu_list.setMinimumSize(QtCore.QSize(300, 0))
        self.menu_list.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_Light")
        font.setPointSize(12)
        self.menu_list.setFont(font)
        self.menu_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_list.setObjectName("menu_list")
        self.horizontalLayout_8.addWidget(self.menu_list)
        self.count_list = QtWidgets.QListView(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("아리따-돋움(TTF)-Light")
        font.setPointSize(12)
        self.count_list.setFont(font)
        self.count_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.count_list.setObjectName("count_list")
        self.horizontalLayout_8.addWidget(self.count_list)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMinimumSize(QtCore.QSize(110, 50))
        self.label_10.setMaximumSize(QtCore.QSize(110, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.total_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.total_label.setMinimumSize(QtCore.QSize(0, 50))
        self.total_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        self.total_label.setFont(font)
        self.total_label.setText("")
        self.total_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_label.setObjectName("total_label")
        self.horizontalLayout_7.addWidget(self.total_label)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 50))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.managerTab.addTab(self.stock_tab, "")
        self.returnBtn = QtWidgets.QPushButton(management)
        self.returnBtn.setGeometry(QtCore.QRect(390, 10, 100, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnBtn.sizePolicy().hasHeightForWidth())
        self.returnBtn.setSizePolicy(sizePolicy)
        self.returnBtn.setMinimumSize(QtCore.QSize(100, 50))
        self.returnBtn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("아리따-돋움_TTF_SemiBold")
        font.setPointSize(14)
        self.returnBtn.setFont(font)
        self.returnBtn.setObjectName("returnBtn")

        self.retranslateUi(management)
        self.managerTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(management)

    def retranslateUi(self, management):
        _translate = QtCore.QCoreApplication.translate
        management.setWindowTitle(_translate("management", "Dialog"))
        self.label.setText(_translate("management", "순번"))
        self.label_2.setText(_translate("management", "품명"))
        self.label_3.setText(_translate("management", "남은 수량"))
        self.plus_btn.setText(_translate("management", "메뉴 추가"))
        self.managerTab.setTabText(self.managerTab.indexOf(self.menu_tab), _translate("management", "메뉴"))
        self.yearBtn.setText(_translate("management", "연 매출 조회"))
        self.monthBtn.setText(_translate("management", "월 매출 조회"))
        self.dayBtn.setText(_translate("management", "일 매출 조회"))
        self.label_5.setText(_translate("management", "오늘의 매출"))
        self.label_7.setText(_translate("management", "순위"))
        self.label_8.setText(_translate("management", "품명"))
        self.label_9.setText(_translate("management", "수량"))
        self.label_10.setText(_translate("management", "총 매출:"))
        self.label_12.setText(_translate("management", "원"))
        self.managerTab.setTabText(self.managerTab.indexOf(self.stock_tab), _translate("management", "재고"))
        self.returnBtn.setText(_translate("management", "돌아가기"))


#Window class
class initialPage(QtWidgets.QWidget): #초기화면
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        orderUi = initialUi()
        orderUi.setupUi(self)

        orderUi.orderBtn.clicked.connect(self.openMain)
        orderUi.managerBtn.clicked.connect(self.openManager)

        self.setFixedSize(500, 900)

    def openMain(self):
        self.parent().stack.setCurrentIndex(1) #메인화면으로 전환

    def openManager(self):
        self.parent().stack.setCurrentIndex(5) #관리자모드로 전환

class order(QtWidgets.QWidget): #주문하는 메인화면

    def __init__(self, parent=None):
        threading.Timer(120, self.returnInitial).start()#메인화면에 넘어 온 후 2분간 주문 끝내지 않으면 자동으로 초기 화면으로 돌아감

        super().__init__(parent=parent)
        menumainUi = mainUi()
        menumainUi.setupUi(self)

        menumainUi.misterEggBtn.clicked.connect(self.mrOpen)
        menumainUi.americanHamBtn.clicked.connect(self.americanOpen)
        menumainUi.baconDoubleBtn.clicked.connect(self.baconOpen)

        self.setFixedSize(500,900)

    def mrOpen(self):
        orderDetail.orderUi.nameLabel.setText("미스터에그")
        orderDetail.orderUi.detailLabel.setText("기본에 충실한\n"
                                                "그 맛.\n")
        self.parent().stack.setCurrentIndex(2) #상세화면으로 전환

    def americanOpen(self):
        orderDetail.orderUi.nameLabel.setText("아메리칸 햄치즈")
        orderDetail.orderUi.detailLabel.setText("아메리카에서 온\n"
                                                "햄과\n"
                                                "치즈\n")
        self.parent().stack.setCurrentIndex(2) #상세화면으로 전환

    def baconOpen(self):
        orderDetail.orderUi.nameLabel.setText("베이컨 더블치즈")
        orderDetail.orderUi.detailLabel.setText("베이컨과\n"
                                                "치즈의\n"
                                                "만남♥\n")
        self.parent().stack.setCurrentIndex(2) #상세화면으로 전환

    def returnInitial(self):
        ui = orderDetail.orderUi

        ui.avocadoBtn.setCheckState(False)
        ui.pollackBtn.setCheckState(False)
        ui.eggBtn.setCheckState(False)
        ui.bunBtn.setCheckState(False)

        MainWindow.totalCost = 0
        MainWindow.menuName = ""
        MainWindow.topping = ""
        MainWindow.bread = ""

        self.parent().stack.setCurrentIndex(0) #초기 화면으로 전환

class orderDetail(QtWidgets.QWidget): #상세정보 화면

    orderUi = menuUi()

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        #ui = menuUi()
        ui = orderDetail.orderUi
        ui.setupUi(self)

        ui.returnBtn.clicked.connect(self.returnMain) #메뉴 선택 화면으로
        ui.okBtn.clicked.connect(self.doPay) #포장/매장 선택화면으로

        self.setFixedSize(500,900)

    def returnMain(self):
        ui = orderDetail.orderUi

        ui.avocadoBtn.setCheckState(False)
        ui.pollackBtn.setCheckState(False)
        ui.eggBtn.setCheckState(False)
        ui.bunBtn.setCheckState(False)

        MainWindow.totalCost = 0
        MainWindow.menuName = ""
        MainWindow.topping = ""
        MainWindow.bread = ""

        self.parent().stack.setCurrentIndex(1)

    def doPay(self):
        ui = orderDetail.orderUi

        if ui.nameLabel.text() == "미스터에그":
            MainWindow.menuName = "미스터에그"
            MainWindow.totalCost += 3400
        elif ui.nameLabel.text() == "아메리칸 햄치즈":
            MainWindow.menuName = "아메리칸 햄치즈"
            MainWindow.totalCost += 3900
        elif ui.nameLabel.text() == "베이컨 더블치즈":
            MainWindow.menuName = "베이컨 더블치즈"
            MainWindow.totalCost += 4200

        if ui.bunBtn.isChecked():
            MainWindow.bread = "번"

        if ui.eggBtn.isChecked():
            MainWindow.topping = "계란"
            MainWindow.totalCost += 200

        if ui.pollackBtn.isChecked():
            MainWindow.topping = "명란"
            MainWindow.totalCost += 500

        if ui.avocadoBtn.isChecked():
            MainWindow.topping = "아보카도"
            MainWindow.totalCost += 700

        print("메뉴: ", MainWindow.menuName)
        print("빵: ", MainWindow.bread)
        print("토핑: ", MainWindow.topping)
        print("가격: ", MainWindow.totalCost)

        self.parent().stack.setCurrentIndex(3) #포장/매장 선택화면으로 전환

class eatHere(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        ui= takeoutUi()
        ui.setupUi(self)

        ui.returnBtn.clicked.connect(self.returnMenu)
        ui.inBtn.clicked.connect(self.doPay)
        ui.outBtn.clicked.connect(self.changeState)

        self.setFixedSize(500,900)

    def returnMenu(self):
        MainWindow.totalCost = 0
        MainWindow.menuName = ""
        MainWindow.topping = ""
        MainWindow.bread = ""
        self.parent().stack.setCurrentIndex(2)

    def changeState(self):
        MainWindow.eatHere = False
        self.parent().stack.setCurrentIndex(4) #결제화면으로 전환

    def doPay(self):
        self.parent().stack.setCurrentIndex(4) #결제화면으로 전환

class payment(QtWidgets.QWidget): #결제화면

    payUi = paymentUi()

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        ui = payment.payUi
        ui.setupUi(self)

        ui.returnBtn.clicked.connect(self.returnHere)
        ui.moenyInput.returnPressed.connect(self.checkMoney)
        payment.payUi.moenyInput.setText(ui.moenyInput.text())

        self.setFixedSize(500,900)

    def returnHere(self):
        self.parent().stack.setCurrentIndex(3) #매장/포장 선택 화면으로 돌아감

    def checkMoney(self):

        money = payment.payUi.moenyInput.text()
        print("가격: ", money)

        msgBox = QMessageBox()

        if money == str(MainWindow.totalCost):
            msgBox.setWindowTitle("결제 성공")
            msgBox.setText("결제에 성공했습니다.")
            msgBox.setInformativeText("주문번호: %d" %MainWindow.numOrder)
            msgBox.setStandardButtons(QMessageBox.Yes)
            msgBox.setDefaultButton(QMessageBox.Yes)
            MainWindow.numOrder += 1
            threading.Timer(5,self.initial).start()
        else:
            msgBox = QMessageBox()
            msgBox.setWindowTitle("결제 실패")
            msgBox.setText("결제에 실패했습니다.")
            msgBox.setInformativeText("결제 금액을 다시 입력해 주십시오.")
            msgBox.setStandardButtons(QMessageBox.Yes)
            msgBox.setDefaultButton(QMessageBox.Yes)

        msgBox.show()

    def initial(self):

        if MainWindow.numOrder >= 100:
            MainWindow.numOrder = 100
        MainWindow.totalCost = 0
        MainWindow.eatHere = True

        self.parent().stack.setCurrentIndex(0) #메뉴 선택 화면으로 전환

class manager(QtWidgets.QWidget): #관리자모드
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        ui = managementUi()
        ui.setupUi(self)

        ui.returnBtn.clicked.connect(self.returnInitial)

        self.setFixedSize(500, 900)

    def returnInitial(self):
        self.parent().stack.setCurrentIndex(0)

class MainWindow(QtWidgets.QWidget):

    menuName = ""
    totalCost = 0
    eatHere = True  # T = 매장식사, F = 포장
    numOrder = 100
    bread = "기본"
    topping = ""

    if numOrder >= 1000:
        numOrder = 100

    def __init__(self):
        super().__init__()
        self.setFixedSize(500, 900)
        self.setWindowTitle('EGGDROP')
        self.stack = QtWidgets.QStackedLayout(self)
        self.stack0 = initialPage(self)
        self.stack1 = order(self)
        self.stack2 = orderDetail(self)
        self.stack3 = eatHere(self)
        self.stack4 = payment(self)
        self.stack5 = manager(self)
        self.stack.addWidget(self.stack0) #초기화면
        self.stack.addWidget(self.stack1) #메뉴선택화면
        self.stack.addWidget(self.stack2) #메뉴 디테일
        self.stack.addWidget(self.stack3) #포장/매장 선택
        self.stack.addWidget(self.stack4) #결제
        self.stack.addWidget(self.stack5) #관리자모드
        self.show()

app = QtWidgets.QApplication([])
main = MainWindow()
app.exec()