# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EGGDROP(object):
    def setupUi(self, EGGDROP):
        EGGDROP.setObjectName("EGGDROP")
        EGGDROP.resize(500, 900)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        EGGDROP.setPalette(palette)
        EGGDROP.setStyleSheet("backgournd: rgb(255, 255, 255)")
        self.gridLayoutWidget = QtWidgets.QWidget(EGGDROP)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 504, 901))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 700, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.order_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.order_btn.setFont(font)
        self.order_btn.setAutoFillBackground(False)
        self.order_btn.setStyleSheet("background: rgb(184, 61, 0)")
        self.order_btn.setCheckable(False)
        self.order_btn.setObjectName("order_btn")
        self.gridLayout.addWidget(self.order_btn, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.manager_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.manager_btn.setStyleSheet("background:rgba(255, 255, 255, 0)")
        self.manager_btn.setText("")
        self.manager_btn.setObjectName("manager_btn")
        self.gridLayout.addWidget(self.manager_btn, 0, 0, 1, 1)

        self.retranslateUi(EGGDROP)
        QtCore.QMetaObject.connectSlotsByName(EGGDROP)

    def retranslateUi(self, EGGDROP):
        _translate = QtCore.QCoreApplication.translate
        EGGDROP.setWindowTitle(_translate("EGGDROP", "Dialog"))
        self.order_btn.setText(_translate("EGGDROP", "o r d e r"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EGGDROP = QtWidgets.QDialog()
    ui = Ui_EGGDROP()
    ui.setupUi(EGGDROP)
    EGGDROP.show()
    sys.exit(app.exec_())
